spring:
  datasource:
    url: jdbc:h2:file:./hotel;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: bestuser
    password: bestuser
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

#        spring:
#          datasource:
#            url: jdbc:mysql://127.0.0.1:3306/hotel
#            driver-class-name: com.mysql.cj.jdbc.Driver
#            username: bestuser
#            password: bestuser
#          jpa:
#            generate-ddl: true
#            show-sql: true
#            hibernate:
#              ddl-auto: update